# Generated by Django 5.0.6 on 2024-06-02 02:53

import basics.models
from django.db import migrations, models

def create_initial_organization(apps, schema_editor):
    Organization = apps.get_model('basics', 'Organization')
    Organization.objects.create(nombre='Default Organization', direccion='Default Address',
                                telefono='1111-222333', ruc='1111111-9', email='default@default.com', website='www.website.com')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=basics.models.upload_to)),
            ],
        ),
        migrations.RunPython(create_initial_organization),
    ]
