POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{'username': '', 'password':''}
###

POST http://localhost:8000/auth/users/ HTTP/1.1
Content-Type: application/json
 
{"user": {"email":"lola@home.py","password":"loll7777","nombre": "LOL", "apellido":"LOPEZ" },
"group": {"id": "3"}}

###

Put   http://localhost:8000/auth/users/15/ HTTP/1.1
Content-Type: application/json
 
{"user": {"email":"jondan@home.py","password":"jordan7777","nombre": "JORDAN", "apellido":"QUINTERO AQUINO" },
"group": {"id": "1"}}
###

get http://localhost:8000/auth/users/15/ HTTP/1.1
Content-Type: application/json

### 
GET http://localhost:8000/auth/users HTTP/1.1
Content-Type: application/json

### 
GET http://localhost:8000/auth/groups/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8000/auth/token/ HTTP/1.1
Content-Type: application/json

 {"email":"magnus@home.py", "password":"magnus7777"}

###
POST http://localhost:8000/auth/token/refresh/ HTTP/1.1
Content-Type: application/json

 {"refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxMDEwNTE5NSwiaWF0IjoxNzEwMDE4Nzk1LCJqdGkiOiI1YmU0ZjE4NzFiNTY0NTYzOTQ5NWEyYTY3NzI1OGQ1MyIsInVzZXJfaWQiOjExLCJub21icmUiOiJqdWVsaWV0YSJ9.iDzbJKRxGGwcbesIQckGzWS50L71vpK5p-ESbCD6rMc"}



# --------------------------------------------testeo de alumnos-----------------------------------------
   
###
POST    http://localhost:8000/academico/alumnos/ HTTP/1.1
Content-Type: multipart/form-data
 
 {"cedula":"89000005", "nombre":"Lorenzo", "apellido":"Quintana",
                "fecha_nac":"2024-1-4", "telefono":"",
                "nacionalidad":"paraguaya", "direccion":"", 
                "barrio":"san antonio", "alergico_a":"", "edad_primer_grado":"6",
                "curso_jardin":"no", "perfil_psicologico":"", "cantidad_hermanos":"5"}  

###
POST     http://localhost:8000/academico/alumnos/ HTTP/1.1
Content-Type: application/json
  
 {"cedula":"3333525", "nombre":"Ana", "apellido":"Sosa",
                "fecha_nac":"2024-1-04", "telefono":"",
                "nacionalidad":"paraguaya", "direccion":"", 
                "barrio":"Universo", "alergico_a":"", "edad_primer_grado":"6",
                "curso_jardin":"Si", "perfil_psicologico":"", "cantidad_hermanos":"2",
                "genero":"F"}  

###
GET    http://localhost:8000/academico/alumnos/?search=&cedula=33333&page= HTTP/1.1
Content-Type: application/json

###
GET    http://localhost:8000/academico/alumnos/26 HTTP/1.1
Content-Type: multipart/form-data 

#--------------------------------------testeo de grados----------------------------

###
GET http://localhost:8000/academico/grados/ HTTP/1.1

###
post   http://localhost:8000/academico/grados/ HTTP/1.1
Content-Type: application/json

{"nombre":"Septimo Grado", "grado":"7", "nivel":"Tercer Ciclo", "turno":"Tarde", "seccion":"", "es_activo":true}

###
PATCH    http://localhost:8000/academico/grados/9/ HTTP/1.1
Content-Type: application/json

{"nombre":"Noveno Grado", "grado":"9", "nivel":"Tercer Ciclo"}

###
PATCH   http://localhost:8000/academico/grados/8/ HTTP/1.1
Content-Type: application/json

{"es_activo":false}

 
#--------------------------testeo de matriculacion------------------------------------------
### 
get http://localhost:8000/academico/matricula/ HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8000/academico/matricula/ HTTP/1.1
Content-Type: application/json

{"id_alumno":"2", "id_grado":"1", "anio_lectivo":"2024", "fecha_inscripcion":"2024-02-05"}

### 
patch http://localhost:8000/academico/matricula/13/ HTTP/1.1
Content-Type: application/json

{ "es_activo":true}

### 
get http://localhost:8000/academico/matricula/?search=33333&anio_lectivo=2024&es_activo=true&page= HTTP/1.1
Content-Type: application/json

search=33333&anio_lectivo=2024&es_activo=true&page=

#------------------------------------------------------- testeo becas ---------------------------------

###
GET http://localhost:8000/academico/beca/2 HTTP/1.1
Content-Type: application/json

### 
POST  http://localhost:8000/academico/beca/ HTTP/1.1
Content-Type: application/json
 
{"id_beca":"", "nombre":"Familia Numerosa", "descripcion":"Beca para estudiantes con hermanos en la institución",
 "monto":"0","porcentaje":"10","es_activo":false}  

###
PUT  http://localhost:8000/academico/beca/4/ HTTP/1.1
Content-Type: application/json

{"nombre":"Beca Mejor Alumno", "descripcion":"Beca para los alumnos con promedio superior o igual a 4.55",
 "monto":"0","porcentaje":"25","es_activo":"True"}  

###
PATCH  http://localhost:8000/academico/beca/2/ HTTP/1.1
Content-Type: application/json

{"es_activo": true}

#----------------------------------------------- testeo becados ---------------------------------------------------------

###
GET http://localhost:8000/academico/becado/?page=2 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/academico/becado/?id_beca=5&id_matricula=9 HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/academico/becado/?search=9000900 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8000/academico/becado/ HTTP/1.1
Content-Type: application/json
 
{"id_beca":"5","id_matricula":"12", "es_activo":false, "fecha_inicio":"2024-02-15"}

###
PATCH  http://localhost:8000/academico/becado/4/ HTTP/1.1
Content-Type: application/json

{"es_activo": false, "fecha_fin": null}

#------------------------------------------ testeo clientes --------------------------------------------

###
put http://localhost:8000/academico/cliente/1/ HTTP/1.1
Content-Type: application/json
 
{"cedula":"555",
"ruc":"454-5",
"nombre":"Hugo Alberto",
"apellido":"Quintero Aquino",
"telefono":"5258",
"email":"hugo@home.com",
"direccion":"ypane-central",
"tipo":"F"}

###
post http://localhost:8000/academico/cliente/ HTTP/1.1
Content-Type: application/json
 
{"cedula":"888",
"ruc":"",
"nombre":"Carlos",
"apellido":"Lacost",
"telefono":"5124512",
"email":"carlosl@home.com",
"direccion":"central",
"tipo":"F"}

###
GET  http://localhost:8000/academico/cliente/1 HTTP/1.1
Content-Type: application/json

#--------------------testeo responsables ----------------------
###
put http://localhost:8000/academico/responsable/23/ HTTP/1.1
Content-Type: application/json

{
"cliente":"2",
"alumno":"19",
"ocupacion":"Profesora",
"tipo_relacion":"Madre",
"es_activo":true}

### 
get  http://localhost:8000/academico/responsable/ HTTP/1.1
Content-Type: application/json

###  
get  http://localhost:8000/academico/responsable/find/?id_cliente=1&id_alumno=19 HTTP/1.1
Content-Type: application/json

###
POST  http://localhost:8000/academico/responsable/nuevo/ HTTP/1.1
Content-Type: application/json 

{
    "cliente": {
      "cedula": 8989,
      "ruc": "777-9",
      "nombre": "Reinaldo David",
      "apellido": "Quintero Aquino",
      "telefono": "1111111",
      "email": "reinaldo@home.com",
      "direccion": "ypane-central",
      "tipo": "m"
    },
    "ocupacion": "Empresario",
    "tipo_relacion": "tio",
    "es_activo": true,
    "alumno": 2
  }


#-------------------------------alumno search------------------

### 

get  http://localhost:8000/academico/alumnos/?search=jose HTTP/1.1
Content-Type: application/json

### 
get  http://localhost:8000/academico/alumnos/13  HTTP/1.1
Content-Type: application/json
