# Generated by Django 5.0.3 on 2024-03-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=254)),
                ('barrio', models.CharField(max_length=50)),
                ('alergico_a', models.CharField(max_length=50)),
                ('edad_primer_grado', models.IntegerField()),
                ('curso_jardin', models.CharField(max_length=2)),
                ('perfil_psicologico', models.CharField(max_length=254)),
                ('cantidad_hermanos', models.IntegerField()),
                ('fotocarnet', models.ImageField(null=True, upload_to=None)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id_beca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=254)),
                ('monto', models.IntegerField()),
                ('porcentaje', models.IntegerField()),
                ('es_activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('ruc', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=254)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.IntegerField()),
                ('nivel', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['grado'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(null=True)),
                ('anio_lectivo', models.IntegerField(null=True)),
                ('es_activo', models.BooleanField(default=False)),
                ('fecha_desmatriculacion', models.DateField(null=True)),
                ('trabaja', models.BooleanField(null=True)),
                ('es_interno', models.BooleanField(null=True)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('id_grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Becado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('id_beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.beca')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.matricula')),
            ],
            options={
                'unique_together': {('id_beca', 'id_matricula')},
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=254)),
                ('tipo_relacion', models.CharField(max_length=50)),
                ('es_activo', models.BooleanField(null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'alumno')},
            },
        ),
    ]
