# Generated by Django 5.0.3 on 2024-03-11 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=254)),
                ('barrio', models.CharField(max_length=50)),
                ('alergico_a', models.CharField(max_length=50)),
                ('edad_primer_grado', models.IntegerField()),
                ('curso_jardin', models.CharField(max_length=2)),
                ('perfil_psicologico', models.CharField(max_length=254)),
                ('cantidad_hermanos', models.IntegerField()),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.IntegerField()),
                ('nivel', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=15)),
                ('seccion', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(null=True)),
                ('anio_lectivo', models.IntegerField(null=True)),
                ('es_activo', models.BooleanField(default=False)),
                ('fecha_desmatriculacion', models.DateField(null=True)),
                ('id_alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('id_grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
            ],
        ),
    ]
