# Generated by Django 5.0.3 on 2024-03-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alumno_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='curso_jardin',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fotocarnet',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='perfil_psicologico',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
