# Generated by Django 5.0.3 on 2024-04-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_alter_alumno_curso_jardin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso_jardin',
        ),
    ]
