# Generated by Django 5.0.3 on 2024-04-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0008_alumno_curso_jardin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alergico_a',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
