# Generated by Django 5.0.3 on 2024-04-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0009_alter_alumno_alergico_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='es_activo',
            field=models.BooleanField(default=False),
        ),
    ]
