# Generated by Django 5.0.3 on 2024-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_grado_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='seccion',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
