# Generated by Django 5.0.3 on 2024-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_alter_grado_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='barrio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cantidad_hermanos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad_primer_grado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='beca',
            name='monto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beca',
            name='porcentaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='grado',
            name='grado',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grado',
            name='turno',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='es_interno',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='trabaja',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
