# Generated by Django 5.0.3 on 2024-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0012_alter_alumno_barrio_alter_alumno_cantidad_hermanos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
