# Generated by Django 5.0.3 on 2024-04-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0013_alter_cliente_id_alter_responsable_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id',
            new_name='id_cliente',
        ),
    ]
