# Generated by Django 5.0.3 on 2024-04-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_rename_id_cliente_id_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsable',
            old_name='alumno',
            new_name='id_alumno',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='cliente',
            new_name='id_cliente',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='id',
            new_name='id_responsable',
        ),
        migrations.AlterUniqueTogether(
            name='responsable',
            unique_together={('id_cliente', 'id_alumno')},
        ),
    ]
