# Generated by Django 5.0.6 on 2024-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_rename_alumno_responsable_id_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('vencimiento_pagos', models.IntegerField()),
                ('es_activo', models.BooleanField(default=False)),
            ],
        ),
    ]
