# Generated by Django 5.0.6 on 2024-06-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0018_remove_beca_porcentaje_beca_tipo_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='tipo_monto',
            field=models.IntegerField(choices=[(1, 'PORCENTAJE'), (2, 'MONTO FIJO')], default=0),
        ),
    ]
