# Generated by Django 5.0.6 on 2024-06-16 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0019_alter_beca_tipo_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='id_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='academico.alumno'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to='academico.cliente'),
        ),
    ]
