# Generated by Django 5.0.6 on 2024-06-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0021_alter_responsable_id_alumno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-periodo']},
        ),
    ]
