# Generated by Django 5.0.6 on 2024-07-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlstock',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
