# Generated by Django 5.0.6 on 2024-07-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_controlstock_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlstock',
            name='cantidad_productos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
