# Generated by Django 5.0.6 on 2024-05-15 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_rename_alumno_responsable_id_alumno_and_more'),
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipo_pago',
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_pago', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.cliente')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='arancel',
            name='id_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.comprobante'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.comprobante'),
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('nro_recibo', models.IntegerField()),
                ('id_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pagos', models.IntegerField()),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField()),
                ('nro_pago', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_activo', models.BooleanField()),
                ('id_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.comprobante')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalleVenta', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.venta')),
            ],
        ),
    ]
