# Generated by Django 5.0.6 on 2024-05-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_rename_alumno_responsable_id_alumno_and_more'),
        ('caja', '0002_remove_factura_fecha_remove_factura_id_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='grados',
            field=models.ManyToManyField(related_name='productos', to='academico.grado'),
        ),
    ]
