# Generated by Django 5.0.6 on 2024-05-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_producto_grados'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_mensual',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
