# Generated by Django 5.0.6 on 2024-05-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_producto_es_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='es_mensual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
