# Generated by Django 5.0.6 on 2024-05-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_remove_recibo_id_comprobante_comprobante_id_timbrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timbrado',
            name='establecimiento',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timbrado',
            name='punto_expedicion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timbrado',
            name='ultimo_numero',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
