# Generated by Django 5.0.6 on 2024-06-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_venta_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='monto',
            new_name='precio',
        ),
    ]
