# Generated by Django 5.0.6 on 2024-06-07 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_rename_monto_detalleventa_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoventa',
            name='id_comprobante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.comprobante'),
        ),
    ]
