# Generated by Django 5.0.6 on 2024-06-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0016_periodo'),
        ('caja', '0011_alter_producto_grados'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='grados',
            field=models.ManyToManyField(blank=True, related_name='productos', to='academico.grado'),
        ),
    ]
