# Generated by Django 5.0.6 on 2024-06-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0012_producto_iva_alter_producto_grados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobante',
            options={'ordering': ['-fecha']},
        ),
    ]
