# Generated by Django 5.0.6 on 2024-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_compra_detallecompra_flujocaja_extraccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
