# Generated by Django 5.0.6 on 2024-06-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0015_comprobante_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha']},
        ),
    ]
