# Generated by Django 5.0.6 on 2024-06-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0016_alter_compra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujocaja',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
