# Generated by Django 5.0.6 on 2024-06-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0017_alter_flujocaja_hora_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujocaja',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flujocaja',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flujocaja',
            name='hora_apertura',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
