# Generated by Django 5.0.6 on 2024-06-19 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0021_alter_compra_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_flujoCaja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra', to='caja.flujocaja'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='hora',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
