# Generated by Django 5.0.6 on 2024-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0022_compra_hora_alter_compra_id_flujocaja_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-tiempo_alta']},
        ),
        migrations.AddField(
            model_name='compra',
            name='tiempo_alta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
