# Generated by Django 5.0.6 on 2024-06-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0023_alter_compra_options_compra_tiempo_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='hora',
        ),
    ]
