# Generated by Django 5.0.6 on 2024-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0024_remove_compra_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujocaja',
            name='entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='flujocaja',
            name='salida',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
