# Generated by Django 5.0.6 on 2024-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0025_flujocaja_entrada_flujocaja_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujocaja',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flujocaja',
            name='salida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
