# Generated by Django 5.0.6 on 2024-06-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0022_alter_periodo_options'),
        ('caja', '0027_alter_flujocaja_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id_tipoActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_activo', models.BooleanField(default=False)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.periodo')),
                ('id_tipoActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.tipoactividad')),
            ],
        ),
        migrations.CreateModel(
            name='PagoActividad',
            fields=[
                ('id_pagoActividad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PagoActividad', to='caja.actividad')),
                ('id_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.comprobante')),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.matricula')),
            ],
        ),
    ]
