# Generated by Django 5.0.6 on 2024-06-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0029_actividad_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoactividad',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
    ]
