# Generated by Django 5.0.6 on 2024-07-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0031_ajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
