# Generated by Django 5.0.6 on 2024-07-05 01:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0032_producto_stock_minimo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ajuste',
            new_name='AjusteDetalle',
        ),
    ]
