# Generated by Django 5.0.6 on 2024-07-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0033_rename_ajuste_ajustedetalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ajustedetalle',
            old_name='id_ajuste',
            new_name='id_ajusteDetalle',
        ),
    ]
