# Generated by Django 5.0.6 on 2024-07-12 00:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0034_rename_id_ajuste_ajustedetalle_id_ajustedetalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AjusteDetalle',
            new_name='BajaInventario',
        ),
    ]
