# Generated by Django 5.0.6 on 2024-07-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0035_rename_ajustedetalle_bajainventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajainventario',
            old_name='id_ajusteDetalle',
            new_name='id_bajaInventario',
        ),
    ]
