# Generated by Django 5.0.6 on 2024-08-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0040_rename_monto_cierre_flujocaja_monto_flujocaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujocaja',
            name='monto_flujoCaja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
